### ISSUE TITLE
Suggestion: Documentation

### ISSUE THREAD

**Issue by RepeaterCreeper** [alexinman/clashtracker#22]
Maybe you should have a documentation on how to set this up. I usually can setup these type of stuff in a couple minutes but this one is just confusing for me. And also a demo website just so that we can see what it really does... even picture is perfectly fine.

**Comment by alexinman** [comment]
I have a website setup at clashtracker.ca

**Comment by alexinman** [comment]
I'll work on documentation for setting up your own instance of the website, but I can't promise it will be ready anytime soon. Pretty busy with full time work and other activities. But I'll do my best to get something put together eventually.
