### ISSUE TITLE
Undefined property in /showMessages.php

### ISSUE THREAD

**Issue by alexinman** [alexinman/clashtracker#59]
When there are no messages to display these lines are giving warnings because they're not set. Should check if they're set (using `isset`) before displaying
https://github.com/alexinman/clashtracker/blob/develop/www/showMessages.php#L11
https://github.com/alexinman/clashtracker/blob/develop/www/showMessages.php#L4

**Comment by RHITNL** [comment]
Not sure if this is the fix you were thinking of :)

**Comment by alexinman** [comment]
Fixed by #61
