### ISSUE TITLE
War Messages

### ISSUE THREAD

**Issue by alexinman** [alexinman/clashtracker#64]
> 1.       When we assign enemy to our players, we always have 1 player (per TH level) that is the sweeper. That player does not get anything assigned but cleans up the mess if needed. As we create the attack list manual on our phones or tablets, we always write a comment below the list with information like 
“Please do the first attack within 16 hours after start of the war. If this is not possible for whatever reason, please let the clanmanagement know. Twisted will sweep TH10 and John Doe will sweep TH9 and below”

Some way of adding a message to a war that all players can read during the war would be nice.

**Comment by alexinman** [comment]
War messages were added with this commit: https://github.com/alexinman/clashtracker/commit/f7134347aa941ee3c13ac3f498128850c6f8eceb

Should test on <a href="http://staging-clashtracker.herokuapp.com">staging-clashtracker.herokuapp.com</a> before closing this issue and merging into `master`.

@RHITNL Could you check that out for me, make sure that looks good and works for you?

**Comment by RHITNL** [comment]
Seems to work great. Noticed only one thing. You are not able to use enters in text. You can input them but after saving the enters are stripped.
Ideally this message should be visible in warplaning page (does not exist yet) or on all pages/tabs in war.php

**Comment by alexinman** [comment]
I'll take a look and try to fix the new line (enter) problem you mentioned when I get home this evening.

When I work on the war planning page, I'll make sure to have the war messages as an option there as well.

**Comment by alexinman** [comment]
Alright, I fixed the new line (enter) problem you mentioned with this commit: https://github.com/alexinman/clashtracker/commit/27c590eefc48fe3edf3128b7304e2575849d72eb

@RHITNL Mind retesting just to make sure I didn't miss anything else? :)

**Comment by RHITNL** [comment]
This is the result 
![image](https://cloud.githubusercontent.com/assets/6173448/17683517/d2f3a6bc-6353-11e6-919c-3b01ef3745aa.png)
Not fixed yet I'm afraid. Of to bed now :)

**Comment by RHITNL** [comment]
Have looked at it a little closer and it seems to work partly. Create a new message will show the above just after the save. On a refresh, the br is gone and it show a new line like it should. The other HTML (a href) is still the same (so not parsed as HTML)
When you edit the message and add another new line and save, both new lines are shown as br and on manual refresh again correct.
Problem seems to be in the ajax call after saving but couldn't get it to work properly

**Comment by alexinman** [comment]
I know how to fix the problem. I have a partial fix in my local code at home (not with me).

I meant to ask you, though, but I've just been busy the past day, do you want to be able to put links in there? I am intentionally sanitising the message so that users can't inject HTML code into the website; that is a security vulnerability. If you want to be able to put a link into the message, I can parse through the message and create a  clickable link for any URL that is in the message. Would that work for you?

**Comment by RHITNL** [comment]
maybe some basic HTML like new line, bold text. Don't think an URL will be needed and could always be added later when it is needed after all.

**Comment by alexinman** [comment]
Alright. I'll work on that this evening when I get home from work.
I'll include all of these text formatting HTML tags: http://www.w3schools.com/html/html_formatting.asp

**Comment by alexinman** [comment]
@RHITNL Alright... I think I have it working now. Could you take another look for me?
The following should work:
 - New lines get formatted properly
 - The HTML tags on this page get used correctly, but all other HTML tags get sanitised so they don't mess up the page: http://www.w3schools.com/html/html_formatting.asp
 - URLs should be linked automatically

Example:
![screen shot 2016-08-17 at 10 04 39 pm](https://cloud.githubusercontent.com/assets/6303087/17758539/a61bfce2-64c6-11e6-81af-a71011a2ebb1.png)
![screen shot 2016-08-17 at 10 03 25 pm](https://cloud.githubusercontent.com/assets/6303087/17758538/a61885da-64c6-11e6-86a7-88a00590b8e4.png)

**Comment by RHITNL** [comment]
Great! seems to work a lot better.
Found one small issue (sorry). When filling a http or https URL holding a dash the html create a invalid URL. My business website for instance, https://rh-it.nl became partly clickable after save. -it.nl does not.
See source `<a href="https://rh">https://rh</a>-it.nl<br><a href="http://rh">http://rh</a>-it.nl`

**Comment by RHITNL** [comment]
Pushed a fix to dev which was tested multiple time. Work OK on my server. Please check my code and let me know what you think of it

**Comment by alexinman** [comment]
Found a couple of minor edge case issues:
New lines are being included in the URL, because of the `<br>` that gets put in there. The `<` and `>` characters shouldn't be matched by the regex.
![screen shot 2016-08-18 at 9 11 26 am](https://cloud.githubusercontent.com/assets/6303087/17773238/c9754b46-6523-11e6-9e45-dbf4e91b0669.png)
The quote `"` at the end of the URL is being included in the URL as well. The regex probably should match that as well.
![screen shot 2016-08-18 at 9 11 29 am](https://cloud.githubusercontent.com/assets/6303087/17773239/c97632b8-6523-11e6-9cda-ffdbc02b7cac.png)
Also, special characters shouldn't be matched:
![screen shot 2016-08-18 at 9 24 37 am](https://cloud.githubusercontent.com/assets/6303087/17773646/a5bc1f8e-6525-11e6-8eff-8538e00ce7e6.png)

**Comment by alexinman** [comment]
We could try this `(htt|ft|sc)p(s)?://[a-zA-Z0-9.?&=\-/_]+` for the regex... not sure though...

**Comment by RHITNL** [comment]
I tested this on on www.regexr.com and that seems to do what we need? Agree?
(?:htt|ft|sc)?(p)?(s)?(?:\:\/\/)?(?:www.)?(([A-Za-z0-9-]+\.)*[A-Za-z0-9-]+\.[A-Za-z]+)(?:\/.*)?

**Comment by alexinman** [comment]
That matches the following:
- `htt://hello.com`
- `://hello.com`

Possibly this?
`((htt|ft|sc)p(s)?:\/\/)?(www.)?(([A-Za-z0-9-]+\.)*[A-Za-z0-9-]+\.[A-Za-z]+)(?:\/.*)?`

**Comment by alexinman** [comment]
I found a PHP library for parsing URLs out of strings and making them clickable:
https://gist.github.com/nomanson/3259843

I've added it to our code and used it. It seems to work for all what I've tested.
@RHITNL want to test it out make sure it works for you as well?

**Comment by RHITNL** [comment]
Updated to latest branche and looks like it is all running OK. Had some errors in PHP about Non-static method in several lines but reading about this told me this is partly because of the the way I have set the error output. Changed it and now it is all ok

**Comment by alexinman** [comment]
So we're good to close this issue now? I believe it works pretty good now.

**Comment by RHITNL** [comment]
Yes, I will close this.
